
stages:
  - test

test:check-commits:
  image: alpine
  stage: test
  before_script:
    # Install dependencies
    - apk add --no-cache git bash
    # Rename the branch we're on, so that it's not in the way for the
    # subsequent fetch. It's ok if this fails, it just means we're not on any
    # branch.
    - git branch -m temp-branch || true
    # Git trick: Fetch directly into our local branches instead of remote
    # branches.
    - git fetch origin 'refs/heads/*:refs/heads/*'
    # Get last remaining tags, if any.
    - git fetch --tags origin
    - git clone http://github.com/mendersoftware/mendertesting /tmp/mendertesting
  script:
    # Check commit compliance.
    - /tmp/mendertesting/check_commits.sh ${MENDERTESTING_ARGS}
